### ISSUE TITLE
Can both twig and standard templates be used together?

### ISSUE THREAD

**Issue by bizmate** [yiiext/twig-renderer#42]
Is it possible to use two renderers instead of only one?
For instance any was such that when calling
```
$this->render('settings', array(
		'model' => $model,
                'viewMode' => $viewMode,
                'maintenanceMode' => $maintenanceMode
));
```
the `settings.php` template is used but when
```
$this->renderTwig('account', array(
		'model' => $model,
                'viewMode' => $viewMode,
                'maintenanceMode' => $maintenanceMode
));
```
is called the *account.html.twig* file is used instead?

or something even similar to the above such as a 
`$this->render('@templates/account.html.twig'`

**Comment by samdark** [comment]
Not in Yii 1.1. Yii 2.0 and Yii 3.0 have support for multiple view renderers at the same time.
